#!/bin/bash

echo
read -rsp $'Should we install get_linux_version for check_mk [y/n] ?\n' -n1 PLUGIN

if [ $PLUGIN == "y" ]; then


mkdir -p /usr/lib/check_mk_agent/local/
cp  check_mk_local_plugin_get_linux_version /usr/lib/check_mk_agent/local/get_linux_version

fi
