#!/bin/python


import os, shutil, stat
from os.path import join, getsize
for root, dirs, files in os.walk('check_plugins'):
	for file in files:
		print "Install " + file + " ? "
		print "y / n "		
		install=raw_input()
		
		if install == "y" :
			print "install"
			print root
			if os.path.isdir("/usr/lib/check_mk_agent/local/") is False :
				os.makedirs ("/usr/lib/check_mk_agent/local/")
			shutil.copy( os.path.join (root , file) , "/usr/lib/check_mk_agent/local/" ) 
						
			
			os.chmod ( os.path.join("/usr/lib/check_mk_agent/local/" , file ) , 0o700)
		else:
			print "skipping"
	
	
	
	
	