#!/bin/python
# -*- coding: utf-8 -*-
from  subprocess import check_output
import re


lspci=check_output(["lspsi"])

# Alle Umbrüche ( 0xA0 = LF) als \n anzeigen lassen:
lspci = repr(lspci)#

# Alle \n in \\ umwandeln
# den \ von \n muss man im regex auch escapten: \\ = \ 
lspci = re.sub(r'\\n', "\\\\n", lspci)
print  '0 Linux_Hardware - OK  Output of lspci: ' + lspci